version: '3.8'
services:
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-5000}:5000"
    environment:
      - FLASK_ENV=production
    volumes:
      - .:/app
volumes:
  chrome_data:
