services:
  - type: web
    name: flask-app
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
    buildCommand: docker build -t flask-app .
    startCommand: docker run -p $PORT:5000 flask-app
